name: Main-Deploy-Infra

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  CLIENT_ID: 6c432122-ec6f-481b-9a18-5fc2a9d89a68
  TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
  SUBSCRIPTION_ID: 651dc44c-5d8e-48da-8cd3-cd79224ac290
  RG: xstof-bidding

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-env:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ ENV.CLIENT_ID }}
          tenant-id: ${{ ENV.TENANT_ID }}
          subscription-id: ${{ ENV.SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az deployment group create --resource-group ${{ ENV.RG }} \
            --template-file container-app-env.bicep \
            --parameters containerAppEnvName='xstof-bidding-dev-containerAppsEnv' \
                         containerAppLogAnalyticsName='xstof-bidding-dev-LA'
          
  check-folder-changes:
    runs-on: 'ubuntu-latest'
    # Declare outputs for next jobs
    outputs:
      api_changed: ${{ steps.check_folder_changed.outputs.api_changed }}
      web_changed: ${{ steps.check_folder_changed.outputs.web_changed }}
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      id: check_folder_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under folder has changed (added, modified, deleted)
        $APIDiff = $diff | Where-Object { $_ -match '^BiddingAPI/' }
        $WEBDiff = $diff | Where-Object { $_ -match '^BiddingWeb/' }
        $HasAPIDiff = $APIDiff.Length -gt 0
        $HasWEBDiff = $WEBDiff.Length -gt 0

        # Set the output named "api_changed"
        Write-Host "::set-output name=api_changed::$HasAPIDiff"
        
        # Set the output named "web_changed"
        Write-Host "::set-output name=web_changed::$HasWEBDiff"

  build-image-api-calling-wf:
    needs: [build-env, check-folder-changes]
    if: needs.check-folder-changes.outputs.api_changed == 'True'
    uses: ./.github/workflows/api.yml

  output-api-url:
    runs-on: ubuntu-latest
    needs: [build-image-api-calling-wf]
    if: needs.check-folder-changes.outputs.api_changed == 'True'
    steps:
      - id: output-api-url
        run: echo ${{ needs.build-image-api-calling-wf.outputs.biddingapiurl }}

  build-image-web-calling-wf:
    needs: [build-env, check-folder-changes]
    if: needs.check-folder-changes.outputs.web_changed == 'True'
    uses: ./.github/workflows/web.yml
